### ISSUE TITLE
Is there a way to add tags to the notes?

### ISSUE THREAD

**Issue by xverges** [amarmaduke/ankideckffs#1]
I am new to Anki, but keeping notes under git seemed like the Right Thing and I am very happy to have found this plugin. Thanks!
**Is there a way to add tags to the text files?**

**Comment by BrandonBrowning** [comment]
@amarmaduke :+1: :shipit:

![](https://pbs.twimg.com/media/CaS4jhbVIAEAfEP.jpg)

:hankey:

**Comment by amarmaduke** [comment]
There is no way to add tags on the file system currently. A couple of methods I considered were having a special [[tags]] field, or having a directory act like a tag instead of a subdeck.

How important would tags be to you? It seemed like they were more or less ignored when I read around.

**Comment by amarmaduke** [comment]
added by #2
